import { HomeLoanFormData } from './types';

export const sampleHomeData: Partial<HomeLoanFormData> = {
  applicationDate: '2026-04-29',
  applicantEntityType: 'Individual',
  coApplicantEntityType: 'Individual',
  guarantorEntityType: 'Individual',
  applicantOwnedHouse: true,
  applicantPersonal: {
    fullName: 'Arun Kumar V',
    dob: '1988-06-15',
    gender: 'Male',
    fatherName: 'Varadhan',
    mobile: '9884488440',
    maritalStatus: 'Married',
    spouseName: 'Lakshmi',
    numberOfDependents: '2',
    education: 'Graduate',
    educationOther: '',
    religion: 'Hindu',
    religionOther: '',
    category: 'General',
    categoryOther: '',
  },
  coApplicantPersonal: {
    fullName: 'Lakshmi Arun',
    dob: '1992-08-20',
    gender: 'Female',
    fatherName: 'Ramachandran',
    mobile: '9884488441',
    maritalStatus: 'Married',
    spouseName: 'Arun Kumar',
    numberOfDependents: '0',
    education: 'Graduate',
    educationOther: '',
    religion: 'Hindu',
    religionOther: '',
    category: 'General',
    categoryOther: '',
  },
  guarantorPersonal: {
    fullName: 'Suresh Kumar',
    dob: '1985-03-10',
    gender: 'Male',
    fatherName: 'Manickam',
    mobile: '9884488442',
    maritalStatus: 'Married',
    spouseName: 'Deepa',
    numberOfDependents: '1',
    education: 'Post Graduate',
    educationOther: '',
    religion: 'Hindu',
    religionOther: '',
    category: 'General',
    categoryOther: '',
  },
  loanDetails: {
    loanAmount: '4500000',
    tenure: '120',
    interestRate: '9.5',
    emi: '60000',
  },
  applicantContact: {
    communicationAddress: {
      fullAddress: '12, MG Road, Adyar, Chennai - 600020',
      landmark: 'Near Gandhi Statue',
      city: 'Chennai',
      district: 'Chennai',
      state: 'Tamil Nadu',
      pinCode: '600020',
    },
    permanentSameAsCommunication: true,
    permanentAddress: {
      fullAddress: '12, MG Road, Adyar, Chennai - 600020',
      landmark: 'Near Gandhi Statue',
      city: 'Chennai',
      district: 'Chennai',
      state: 'Tamil Nadu',
      pinCode: '600020',
    },
    alternateMobile: '4424424422',
    email: 'arun.v@example.com',
  },
  coApplicantContact: {
    communicationAddress: {
      fullAddress: '12, MG Road, Adyar, Chennai - 600020',
      landmark: 'Near Gandhi Statue',
      city: 'Chennai',
      district: 'Chennai',
      state: 'Tamil Nadu',
      pinCode: '600020',
    },
    permanentSameAsCommunication: true,
    permanentAddress: {
      fullAddress: '12, MG Road, Adyar, Chennai - 600020',
      landmark: 'Near Gandhi Statue',
      city: 'Chennai',
      district: 'Chennai',
      state: 'Tamil Nadu',
      pinCode: '600020',
    },
    alternateMobile: '',
    email: 'lakshmi.a@example.com',
  },
  guarantorContact: {
    communicationAddress: {
      fullAddress: '45, West Mada Street, Mylapore, Chennai - 600004',
      landmark: 'Near Kapaleeshwarar Temple',
      city: 'Chennai',
      district: 'Chennai',
      state: 'Tamil Nadu',
      pinCode: '600004',
    },
    permanentSameAsCommunication: true,
    permanentAddress: {
      fullAddress: '45, West Mada Street, Mylapore, Chennai - 600004',
      landmark: 'Near Kapaleeshwarar Temple',
      city: 'Chennai',
      district: 'Chennai',
      state: 'Tamil Nadu',
      pinCode: '600004',
    },
    alternateMobile: '',
    email: 'suresh.k@example.com',
  },
  applicantResidence: {
    residence: 'Owned',
    yearsOfStay: '15',
  },
  coApplicantResidence: {
    residence: 'Owned',
    yearsOfStay: '10',
  },
  guarantorResidence: {
    residence: 'Owned',
    yearsOfStay: '20',
  },
  applicantBank: {
    bankName: 'HDFC Bank',
    branch: 'Adyar',
    accountType: 'Savings',
    accountNo: '50100223344556',
    accountSince: '2015',
    ifscCode: 'HDFC0001234',
    avgDebitPerMonth: '40000',
    avgCreditPerMonth: '85000',
  },
  coApplicantBank: {
    bankName: 'ICICI Bank',
    branch: 'Adyar',
    accountType: 'Savings',
    accountNo: '678901234567',
    accountSince: '2018',
    ifscCode: 'ICIC0005678',
    avgDebitPerMonth: '20000',
    avgCreditPerMonth: '45000',
  },
  applicantEmployment: {
    establishmentName: 'Tech Solutions Pvt Ltd',
    designation: 'Senior Manager',
    yearsOfEmployment: '8',
    ctcPerAnnum: '1200000',
  },
  coApplicantEmployment: {
    establishmentName: 'Green Systems',
    designation: 'Accountant',
    yearsOfEmployment: '5',
    ctcPerAnnum: '600000',
  },
  propertyDetails: {
    propertyType: 'Building Residential',
    propertyTypeOther: '',
    locality: 'Green Valley Layout, Sholinganallur',
    surveyNo: '142/3A',
    pattaNo: '8892',
    landArea: '2400',
    builtUpArea: '1800',
    marketValue: '6500000',
    boundaryNorth: 'Plot 141',
    boundarySouth: 'Main Road',
    boundaryEast: 'Plot 143',
    boundaryWest: 'Park Area',
  },
  kycDocuments: {
    aadhaarCard: { applicantChecked: true, applicantDocNo: '1234 5678 9012', coApplicantChecked: false, coApplicantDocNo: '', guarantorChecked: false, guarantorDocNo: '' },
    panCard: { applicantChecked: true, applicantDocNo: 'ABCDE1234F', coApplicantChecked: false, coApplicantDocNo: '', guarantorChecked: false, guarantorDocNo: '' },
    passport: { applicantChecked: false, applicantDocNo: '', coApplicantChecked: false, coApplicantDocNo: '', guarantorChecked: false, guarantorDocNo: '' },
    drivingLicence: { applicantChecked: false, applicantDocNo: '', coApplicantChecked: false, coApplicantDocNo: '', guarantorChecked: false, guarantorDocNo: '' },
    gasConnection: { applicantChecked: false, applicantDocNo: '', coApplicantChecked: false, coApplicantDocNo: '', guarantorChecked: false, guarantorDocNo: '' },
    waterBill: { applicantChecked: false, applicantDocNo: '', coApplicantChecked: false, coApplicantDocNo: '', guarantorChecked: false, guarantorDocNo: '' },
    electricityBill: { applicantChecked: false, applicantDocNo: '', coApplicantChecked: false, coApplicantDocNo: '', guarantorChecked: false, guarantorDocNo: '' },
    mobilePostpaidBill: { applicantChecked: false, applicantDocNo: '', coApplicantChecked: false, coApplicantDocNo: '', guarantorChecked: false, guarantorDocNo: '' },
    voterIdCard: { applicantChecked: false, applicantDocNo: '', coApplicantChecked: false, coApplicantDocNo: '', guarantorChecked: false, guarantorDocNo: '' },
    rationCard: { applicantChecked: false, applicantDocNo: '', coApplicantChecked: false, coApplicantDocNo: '', guarantorChecked: false, guarantorDocNo: '' },
  },
  preSanctionDocs: {
    saleAgreement: true,
    parentDocuments: true,
    encumbranceCertificate: true,
    pattaChitta: true,
    approvalPlan: true,
    nocBuilder: false,
    bankStatement: true,
    itr: false,
    othersText: '',
  },
  postDisbursementDocs: {
    saleDeedOriginal: false,
    modDeposit: false,
    insurancePolicy: false,
    othersText: '',
  }
};
